### ISSUE TITLE
docs error:wrong link

### ISSUE THREAD

**Issue by lightClouds917** [seata/seata.github.io#129]
can‘t access : https://seata.io/zh-cn/docs/user/configurations090.html

**Comment by lightClouds917** [comment]
I don't find this page in the project

**Comment by lovepoem** [comment]
@zjinlei Please have a look

**Comment by lightClouds917** [comment]
@zjinlei  I have tried to fix,but I don't find the 090.html,only find 090.md

**Comment by lovepoem** [comment]
> @zjinlei I have tried to fix,but I don't find the 090.html,only find 090.md

Yes， that‘s it . The framework will generate a  090.html from 090.md

**Comment by lovepoem** [comment]
```0.9.0.1前版本 <a href="./configurations090.md">点击这里</a>```
It seems should be this , It runs success

**Comment by lightClouds917** [comment]
done

**Comment by lovepoem** [comment]
closed via https://github.com/seata/seata.github.io/pull/131
