### ISSUE TITLE
 Springboot1.5的jackson版本不兼容的解决方案应该在文档中说明

### ISSUE THREAD

**Issue by Zane-Zeng** [seata/seata.github.io#152]
### Springboot1.5 集成seata报错：
**环境描述**：springboot：1.5.14 springcloud：Edgware.RELEASE seata：0.9.0
**错误描述**：正常启动，但是调用api出错，无法提交事务。
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.jsontype.TypeSerializer.typeId(Ljava/lang/Object;Lcom/fasterxml/jackson/core/JsonToken;)Lcom/fasterxml/jackson/core/type/WritableTypeId;
**解决方案**：应该同时将以下三个包版本全局替换为2.9.9，在项目的根依赖加入以下依赖：

                        <dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-databind</artifactId>
				<version>2.9.9</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-core</artifactId>
				<version>2.9.9</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-annotations</artifactId>
				<version>2.9.9</version>
			</dependency>

**Comment by lovepoem** [comment]
![image](https://user-images.githubusercontent.com/827112/71522518-f4612480-28ff-11ea-8ac9-f682e81e5112.png)
