### ISSUE TITLE
文档中状态机设计器演示地址失效了

### ISSUE THREAD

**Issue by fantasylion** [seata/seata.github.io#238]
失效地址：
状态机设计器演示地址: http://seata.io/saga_designer/index.html
状态机设计器视频教程: http://seata.io/saga_designer/vedio.html

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/125036412-8d602680-e0c5-11eb-88d5-5876e4738c0a.png)
work fine.
