### ISSUE TITLE
[Proposal] resolve the conflict issue of generated htmls 

### ISSUE THREAD

**Issue by lovepoem** [seata/seata.github.io#25]
How ot resolve the conflict issue of generated htmls ? I think we an do :

1 . Create `develop` branch , remove  generated htmls and add the directory to .gitignore file, see [pr-24 ](https://github.com/seata/seata.github.io/pull/24)
2 . The owner of this repo please make `develop` branch as `default` branch, then the source md files should be submitted here 
3 . The `master` branch then should be as static branch for the github pages
4 . Please prepare a CI server to do the work of generating htmls . The machine can run a crontab task to monitor the code of this repo ,  if the develop branch  have some new commits ,  then generate htmls and push to master branch . Noice: please make sure the develop and master branches are isolated from each other

**Comment by slievrly** [comment]
Vote +1, this solution can avoid the generated html file conflicts and let everyone focus only on the source files

**Comment by lovepoem** [comment]
Now it is completed!

The contributors please send prs to develop branch. A crontab  task will generate htmls , and push the files to master branch .

So contributors please just pay attention to develop branch only .
