### ISSUE TITLE
新版本的 nacos-config.txt、nacos-config.sh 找不到了

### ISSUE THREAD

**Issue by liujian969** [seata/seata.github.io#251]
nacos-config.txt、nacos-config.sh  这些脚本都找不到了。 

script文件夹 在1.1 1.2 版本找不到

**Comment by IsZouTao** [comment]
是的，新版的seata，配置文件位于seata\script\server\config下。

**Comment by slievrly** [comment]
@liujian969 @IsZouTao https://github.com/seata/seata/tree/develop/script/config-center
