### ISSUE TITLE
seata在spring 如何通过指定spring.profile.active等参数来选择不同的seata配置文件

### ISSUE THREAD

**Issue by xiaosazixian** [seata/seata.github.io#260]
一般项目都会选用不同的配置文件，不管是通过spring.profile.active来指定环境，还是在配置中心中指定不同的环境，都可以通过启动参数来选择不同的环境的配置。
我想问的是，seata能不能不同环境按照不同的seata服务器，客户端应用在启动时通过指定不同的参数来选择连接到哪个seata服务器？

**Comment by slievrly** [comment]
@xiaosazixian currently support `spring.profile.active` , you can define some application-$env.yml.
