### ISSUE TITLE
seata-server1.3.0db模式启动失败

### ISSUE THREAD

**Issue by tlinsion** [seata/seata.github.io#276]
seata-server1.3.0启动的时候用db模式，启动失败。用的apollo配置中心。
这个registry.conf里的配置内容
registry {
  type = "eureka"
  eureka {
    serviceUrl = "http://172.16.194.139:18080/eureka"
    application = "default"
    weight = "1"
  }
}

config {
  type = "apollo"
  apollo {
    appId = "seata-server"
    apolloMeta = "http://172.16.194.139:8080/"
    namespace = "application"
  } 
}
![image](https://user-images.githubusercontent.com/16912535/91788888-f6724480-ec3f-11ea-9e79-c408889ec212.png)
![image](https://user-images.githubusercontent.com/16912535/91788925-08ec7e00-ec40-11ea-83f0-b5040016ec2b.png)

**Comment by lvekee** [comment]
使用seata问题请提issues到seata主仓库
