### ISSUE TITLE
博客存在错别字

### ISSUE THREAD

**Issue by PeineLiang** [seata/seata.github.io#277]
官网博客：http://seata.io/zh-cn/blog/tcc-mode-design-principle.html 中：
update 账户表 set 余额 = 余额 -20 where 账户 = A
按照文章的举例，应该要改成：
update 账户表 set 余额 = 余额 -30 where 账户 = A

**Comment by zhouchangming0727** [comment]
还有，文档上有说  用户账户扣款 为‘’借出‘’，业内都是这么叫的吗？
