### ISSUE TITLE
dubbo +nacos +seata 日志提示开启事务,回滚事务但是undo_log中没有新增信息,且实际是没有回滚的

### ISSUE THREAD

**Issue by huwb13329901681** [seata/seata.github.io#281]

**Comment by lvekee** [comment]
使用seata有问题请提issues到seata主仓库，文档问题提issues到这个仓库

事务没有回滚
1、先检查异常是否被catch或者有无熔断降级
异常被catch后或熔断降级后，全局事务便不感知抛出的异常。建议catch异常后返回异常码给事务发起方（TM），然后事务发起方 (TM) 。通过API的方式回滚全局事务。

2、否则请自行debug以下方法：
ExecuteTemplate#execute(List<SQLRecognizer>, StatementProxy<S>, StatementCallback<T,S>, java.lang.Object...)
如果没进入这个方法，说明数据源被没有代理。

如果没进入

if (CollectionUtils.isEmpty(sqlRecognizers)) {
 sqlRecognizers = SQLVisitorFactory.get(statementProxy.getTargetSQL(),dbType);
}
没进去说明xid没有传递
