### ISSUE TITLE
docker运行seata server, SEATA_IP 不支持127.0.0.1与0.0.0.0

### ISSUE THREAD

**Issue by powerfullmac** [seata/seata.github.io#285]
在使用docker来部署seata和nacos的时候遇到了一个问题: 指定了SEATA_IP为127.0.0.1, 但是nacos的服务中显示的是容器的ip, 导致服务无法连接到seata. 但是指定了除127.0.0.1之外的ip就正常可用了. 看了下代码127.0.0.1与0.0.0.0不可用, 麻烦在文档中注明下

**Comment by dennsya** [comment]
你是同一台机器用docker部署seata和nacos，需要把seata的网络设为container，这样就和nacos共享ip和端口，设置127.0.0.1也可以通讯。
Container：创建的容器不会创建自己的网卡，配置自己的IP，而是和一个指定的容器共享IP、端口范围。
container模式：使用 --network=container:NAME_or_ID 指定。
