### ISSUE TITLE
补充Apollo配置中心的说明文档

### ISSUE THREAD

**Issue by wangliang181230** [seata/seata.github.io#288]
使用Apollo配置中心的说明文档补充。
![图片](https://user-images.githubusercontent.com/1527893/97142051-e2a81200-179a-11eb-808c-3cfbed28df07.png)

**Comment by wangliang181230** [comment]
@LiujunjieALiling

**Comment by LiujunjieALiling** [comment]
> @LiujunjieALiling
好的

**Comment by slievrly** [comment]
@LiujunjieALiling @wangliang181230 fix #338
