### ISSUE TITLE
seata1.4.0的server端部署文档写的跟屎一样

### ISSUE THREAD

**Issue by aaakkkcode** [seata/seata.github.io#293]
seata1.4.0的server端部署文档写的跟屎一样，根本无法让人step by step to follow

**Comment by youarenowhere** [comment]
不要说实话

**Comment by a364176773** [comment]
你可以来尝试优化文档，参与社区共建，而不是喷，还有可以把你认为某个社区入门文档写的不错的留言在此处，我们会去借鉴

**Comment by aaakkkcode** [comment]
不是喷，是恼火。既然开原出来，文档怎么能留坑呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月4日(周二) 晚上6:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [seata/seata.github.io] seata1.4.0的server端部署文档写的跟屎一样 (#293)




 
你可以来尝试优化文档，参与社区共建，而不是喷，还有可以把你认为某个社区入门文档写的不错的留言在此处，我们会去借鉴

**Comment by a364176773** [comment]
> 不是喷，是恼火。既然开原出来，文档怎么能留坑呢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年5月4日(周二) 晚上6:56 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [seata/seata.github.io] seata1.4.0的server端部署文档写的跟屎一样 (#293) 你可以来尝试优化文档，参与社区共建，而不是喷，还有可以把你认为某个社区入门文档写的不错的留言在此处，我们会去借鉴 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我完全理解你们的心情，我也是从用户变成贡献者的，文档相对当初我入门的时候已经有所改善了，而且我本人录制的多个视频全是从官网新人部署文档进行介绍的，可能我们有一些闭门造车，身在其中无法知道哪里需要改善，而绝大多数的用户反馈就是写的不好，写的烂，并没有把哪里，那块，该怎么去更好的描述说出来，一味地喷没法解决问题
