### ISSUE TITLE
registry.conf中的 config配置无法指定Nacos的配置空间

### ISSUE THREAD

**Issue by lighterFang** [seata/seata.github.io#308]
使用以下配置，用脚本同步配置的后，只能在pulic找到配置信息 
config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "127.0.0.1:8848"
    namespace = "b79035ae-5f29-44a1-afa3-480d3561c3cc"
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
  }
}

**Comment by slievrly** [comment]
@lighterFang maybe you imported the configuration using public namespace.
