### ISSUE TITLE
官网首页图片都挂了

### ISSUE THREAD

**Issue by garfieldzf8** [seata/seata.github.io#31]
http://seata.io/zh-cn/docs/overview/what_is_seata.html 
官网首页的图片都挂了
![QQ截图20190805103608](https://user-images.githubusercontent.com/15765135/62434946-0386e080-b76d-11e9-9272-3507c7cb208f.jpg)

**Comment by lovepoem** [comment]
https://upload-images.jianshu.io/upload_images/4420767-90b8bf0388953ee8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

It seems that these links of pictures from jianshu.io are restricted,  would you download them and put then into this repo and send a pr ?   @garfieldzf8

**Comment by lovepoem** [comment]
closed via https://github.com/seata/seata.github.io/pull/32
