### ISSUE TITLE
快速开始文档写的不好

### ISSUE THREAD

**Issue by zhouchangming0727** [seata/seata.github.io#310]
应该以更简单明了的方式 书写快速开始，比如 文档没有写undo_log 要在每个微服务涉及的数据库都要建立，我反复查阅博客才理解这个问题的答案。这个文档真的很不方便，很不快速开始。

**Comment by a364176773** [comment]
欢迎参与文档共建

**Comment by slievrly** [comment]
@zhouchangming0727 thanks for feedback, look forward your contribution.
