### ISSUE TITLE
seata和mybatis-plus冲突 

### ISSUE THREAD

**Issue by lizihang4869** [seata/seata.github.io#330]
在使用了seata之后，同时使用mybatis-plus操作数据库会使plus的增强插件都失效，比如plus的分页插件，自动填充功能，尤其是使用了plus的自动填充功能之后seata还会使plus的修改数据报错。希望官方可以重视一下这个问题，毕竟plus在mysql开发过程中确实极大的方便了开发，
https://blog.csdn.net/zihangba/article/details/117440424?spm=1001.2014.3001.5501,您可以看看我发布的这个问题，确实使用了seata之后，mybatis-plus的所有插件功能都失效了。

**Comment by a364176773** [comment]
return factory.getObject();
