### ISSUE TITLE
The english version of what_is_seata is not about seata

### ISSUE THREAD

**Issue by ggndnn** [seata/seata.github.io#36]
[https://seata.io/en-us/docs/overview/what_is_seata.html](https://seata.io/en-us/docs/overview/what_is_seata.html)

**Comment by lovepoem** [comment]
Should be translated from https://seata.io/zh-cn/docs/overview/what_is_seata.html

**Comment by lovepoem** [comment]
Duplicate  of https://github.com/seata/seata.github.io/issues/70
