### ISSUE TITLE
Add document using zookeeper as the registry

### ISSUE THREAD

**Issue by lvekee** [seata/seata.github.io#399]
## Why you need it?
Add document using zookeeper as the registry.
If you want to fix it, please comment "Please assign it to me" is this issue.

增加zookeeper作为注册中心的文档
如果你有兴趣修复这个问题的话, 请在下方留言 Please assign it to me

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by Pinocchio2018** [comment]
Please assign it to me
