### ISSUE TITLE
读隔离和写隔离是如何体现出分布式事务的

### ISSUE THREAD

**Issue by aiyili** [seata/seata.github.io#408]
写隔离举的例子：
两个全局事务Tx1和Tx2，它们使用的本地锁是互斥的吗？Tx1和Tx2两个事务如果是对同一个数据库表进行操作，就没必要使用分布式事务了，直接依赖数据库的隔离特性就可以做到，所以这个地方有点不明白

**Comment by a364176773** [comment]
tx1写了数据A tx2去读数据A，这俩一定是在同一时间去做的吗？你把时间概念加进去，tx1可能早就提交了，但是在全局事务下是属于未提交

**Comment by aiyili** [comment]
加上时间确实是好理解了，谢了
