### ISSUE TITLE
 No serializer found for class java.io.ByteArrayInputStream and no properties

### ISSUE THREAD

**Issue by phshis** [seata/seata.github.io#413]
在使用oracle数据库 插入insert语句包含Timestamp 字段类型时会报错 Jackson序列化出错
No serializer found for class java.io.ByteArrayInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog["sqlUndoLogs"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog["afterImage"]->io.seata.rm.datasource.sql.struct.TableRecords["rows"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row["fields"]->java.util.ArrayList[10]->io.seata.rm.datasource.sql.struct.Field["value"]->oracle.sql.TIMESTAMP["stream"])

**Comment by a364176773** [comment]
通过打包seata源码仓库的seata-plugin自行引入jar来解决
