### ISSUE TITLE
seata启动问题，直接闪退。

### ISSUE THREAD

**Issue by chen-mingyang** [seata/seata.github.io#498]
seata1.0.0版本
nacos1.1.4版本
mysql5.7
jdk1.8.0_341

seata启动后结果，Unrecognized VM option 'MatespaceSize=512m'
![image](https://user-images.githubusercontent.com/68213575/199949005-b331bbe3-aead-483e-9b17-2e939f77c43e.png)

JDK版本，JDK安装在F盘，没有在C盘
![image](https://user-images.githubusercontent.com/68213575/199949113-95fb68a6-e232-486b-a709-8506bbab20c9.png)

启动bat就修改JVM堆区大小
![image](https://user-images.githubusercontent.com/68213575/199950420-f76efba7-c9e1-47f9-8ed3-f255e276d32c.png)
-Xmx1024m -Xms1024m -Xmn512m

配置了file.conf、registry.conf
vgroup_mapping.my_test_tx_group = "fsp_tx_group"
![image](https://user-images.githubusercontent.com/68213575/199950711-dc88238f-74e3-41d2-ac51-752c6a5a97e8.png)
![image](https://user-images.githubusercontent.com/68213575/199950777-38b8be7b-ad64-463f-b44f-d4d16d61b646.png)

**Comment by slievrly** [comment]
It looks like you need to adjust the JVM parameters based on the jdk version.

**Comment by chen-mingyang** [comment]
根据 jdk 版本调整 JVM 参数。
意思是下图中的，这启动文件默认的JVM参数有错误，但我用的是jdk1.8.0_341主流版本，还要区调整seata1.0.0版本启动文件JVM参数？
![image](https://user-images.githubusercontent.com/68213575/200801706-dc5f0574-5804-40b4-a3a2-f55c659dd69f.png)
