### ISSUE TITLE
Seata1.4.2 Client 端seata.nacos.config.dataId 配置 seataServer.properties 后与 Security冲突，导致服务启动失败！！！

### ISSUE THREAD

**Issue by HeGuiHu** [seata/seata.github.io#503]
Spring Boot: 2.3.2.RELEASE
Spring Cloud: Hoxton.SR8
Spring Cloud Alibaba: 2.2.6.RELEASE
Seata: 1.4.2
Spring Security Oauth2: 2.3.4.RELEASE

问题：如标题描述 Seata1.4.2 Client 端 seata.nacos.config.dataId 配置 seataServer.properties 后与 Security冲突，导致服务启动失败，冲突位置：Security => DefaultUserInfoRestTemplateFactory OAuth2ClientContext 
将 seata 版本改为 1.3.x 后项目正常，RM 注册正常。

**Comment by slievrly** [comment]
Please use https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2.2.10-RC1
