### ISSUE TITLE
建议FAQ添加引入Seata后Feign无法使用url调用的说明

### ISSUE THREAD

**Issue by sunyl-git** [seata/seata.github.io#509]
引入Seata后@FeignClient注解的url属性会失效，调用会提示Load balancer does not have available server for client: http://...
错把url当成serviceName解析了。

参考问题：
https://github.com/alibaba/spring-cloud-alibaba/issues/1347

解决方案：
https://github.com/seata/seata/issues/2544

添加理由：
该问题隐藏太深，很难发现这种框架冲突。FeignClient调用url 情况很常见。

**Comment by a364176773** [comment]
可以提个pr吗？

**Comment by sunyl-git** [comment]
> 

可以的。
