### ISSUE TITLE
文档描述问题

### ISSUE THREAD

**Issue by weijiaxiongdx** [seata/seata.github.io#550]
博客部分，讲如何处理悬挂问题时，说“当执行二阶段Cancel方法时，如果发现TCC事务控制表有相关记录，说明二阶段Cancel方法优先一阶段Try方法执行...”，这里有点疑问，不应该是“如果发现TCC事物控制表没有相关记录”吗？还是我理解的有问题，请解答一下，谢谢！

**Comment by a364176773** [comment]
应该是博客笔误,欢迎提交pr修正
