### ISSUE TITLE
使用kubernetes 部署seata不报错

### ISSUE THREAD

**Issue by xingxing122** [seata/seata.github.io#561]
使用官方的kubernetes 部署seata 部署，部署完毕，在nacos 上也没有发现注册服务，seata 也不报错，这样很难排查报错

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/23273577/217136349-19357a91-410c-468f-a706-a6470b208598.png">

<img width="969" alt="image" src="https://user-images.githubusercontent.com/23273577/217136459-a7594630-8ecb-4578-a224-f57d16ddd7b7.png">

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/4820 参考这个issue的讨论结果
