### ISSUE TITLE
关于文档显示不全的bug

### ISSUE THREAD

**Issue by jumtp** [seata/seata.github.io#562]
表格的右边内容不显示
链接: https://seata.io/zh-cn/docs/user/configurations.html 
![屏幕截图 2023-02-08 115641](https://user-images.githubusercontent.com/49558643/217429652-db732bc1-92d8-44a7-a12c-3d182f1607f2.png)

**Comment by jsbxyyx** [comment]
最下方有滚动条，或者你用鼠标选中某个字之后按住鼠标左键往右滑动也可以看到

**Comment by jumtp** [comment]
> 最下方有滚动条，或者你用鼠标选中某个字之后按住鼠标左键往右滑动也可以看到

我知道...按着shift+滚动条也可以的..如果想要同时看到key和change record的话,并不是那么友好

**Comment by slievrly** [comment]
@jumtp 感谢，我先合入看下效果，不行再revert。
