### ISSUE TITLE
seata集成motan,报错io.seata.common.exception.FrameworkException: No available service

### ISSUE THREAD

**Issue by igool** [seata/seata.github.io#604]
seata集成motan,报错io.seata.common.exception.FrameworkException: No available service，请问谁有这方面的经验，不胜感激。

**Comment by igool** [comment]
或者谁有基于seata与motan做过分布式事务的样例？

**Comment by slievrly** [comment]
> seata集成motan,报错io.seata.common.exception.FrameworkException: No available service，请问谁有这方面的经验，不胜感激。

这个报错和集成motan无关.
