### ISSUE TITLE
There are issues with using SQL cases in Chinese

### ISSUE THREAD

**Issue by Gre-make** [seata/seata.github.io#619]
文档->用户文档->SQL参考->DML修饰
Select语句支持中JOIN使用案例多一个">",造成初学者学习误解。

目前文档使用案例：
SELECT col_name1, col_name2 FROM tb1_name JOIN tb2_name>ON tb1_name. col_name1= tb2_name. col_name1

**Comment by slievrly** [comment]
@Gre-make thanks for your feedback.
