### ISSUE TITLE
首页中的 XA 模式中支持 TiDB 是否有误

### ISSUE THREAD

**Issue by GJXAIOU** [seata/seata.github.io#650]
seata 的首页介绍中的 XA 模式目前已经支持 TiDB，但是 TiDB 目前还是不支持 XA 模式，同时在 seata 内部文档介绍中的 XA 模式中又没有 TiDB 了。

首页：https://seata.io/zh-cn/
![image](https://github.com/seata/seata.github.io/assets/22487563/56324068-6115-45b5-9b15-7d63c933ff0c)

内部介绍：https://seata.io/zh-cn/docs/user/datasource.html
![image](https://github.com/seata/seata.github.io/assets/22487563/81759368-9eb3-4567-b8f9-e5d40b7477b6)

**Comment by slievrly** [comment]
copy that.
