### ISSUE TITLE
bug: docs link 404

### ISSUE THREAD

**Issue by yuluo-yx** [seata/seata.github.io#693]
https://seata.io/zh-cn/docs/v1.8/user/configuration/nacos

https://github.com/seata/seata/blob/develop/script/server/config/registry.conf
![image](https://github.com/seata/seata.github.io/assets/77964041/71e374b7-4a6f-42b4-86b6-15152b21135f)

**Comment by liuqiufeng** [comment]
https://github.com/seata/seata.github.io/pull/667
