### ISSUE TITLE
项目服务中引入seata，接口调用出现异常

### ISSUE THREAD

**Issue by liuyaorong** [seata/seata.github.io#706]
Seata服务运行正常，项目服务启动后，向RM注册成功：
<img width="654" alt="3" src="https://github.com/seata/seata.github.io/assets/29117983/7367ddd3-b4ce-4543-9219-69ba0584a1b8">
但是当我在调用指定接口时（使用编程式事务），出现如下异常问题：
<img width="833" alt="1" src="https://github.com/seata/seata.github.io/assets/29117983/20cb5ba5-0f78-4ec6-878d-de938f4c6767">
<img width="1074" alt="2" src="https://github.com/seata/seata.github.io/assets/29117983/4592a7d8-287d-4482-99b7-fdfed6ba9553">
排除代码层面的问题 (本地测试一切正常，可以正常提交或者回滚事务)，麻烦能够帮我解答一下，谢谢。

**Comment by liuyaorong** [comment]
> 请提供使用的mysql版本 Please provide the mysql version used

mysql数据库版本：8.0.32
mysql连接驱动版本：8.0.22

**Comment by liuyaorong** [comment]
> > > 请提供使用的mysql版本 Please provide the mysql version used
> > > mysql数据库版本
> > > 本地库：8.0.35（正常）
> > > 测试库：8.0.32（异常）
> > > mysql连接驱动版本：8.0.22
> 
> 后续版本中对mysql 8 XA模式的处理有优化，请升级seata版本后再试。 The handling of mysql 8 XA mode is optimized in subsequent releases, please upgrade the seata version and try again.

我们现在用的Seata版本是1.5.2，Seata服务的版本要跟随SpringCloud版本(2021.0.4)，否则会出现不兼容的情况。而且为何本地调试正常，测试环境还是一样的配置为何会有这样的问题？

**Comment by liuqiufeng** [comment]
> > > > 请提供使用的mysql版本 Please provide the mysql version used
> > > > mysql数据库版本
> > > > 本地库：8.0.35（正常）
> > > > 测试库：8.0.32（异常）
> > > > mysql连接驱动版本：8.0.22
> > 
> > 
> > 后续版本中对mysql 8 XA模式的处理有优化，请升级seata版本后再试。 The handling of mysql 8 XA mode is optimized in subsequent releases, please upgrade the seata version and try again.
> 
> 我们现在用的Seata版本是1.5.2，Seata服务的版本要跟随SpringCloud版本(2021.0.4)，否则会出现不兼容的情况。而且为何本地调试正常，测试环境还是一样的配置为何会有这样的问题？

mysql 8 在某个版本对XA做了调整。Seata新版本已经做了兼容，请升级后再试。

Seata没有强绑定SpringCloud版本，只需要确保DataSourceProxyXA正常代理数据源即可。参考：https://seata.io/zh-cn/docs/ops/deploy-guide-beginner#%E4%B8%9A%E5%8A%A1%E7%B3%BB%E7%BB%9F%E9%9B%86%E6%88%90client

**Comment by funky-eyes** [comment]
不要截图，发堆栈文本
Don't take screenshots, send stack text

**Comment by liuyaorong** [comment]
> > > > > 请提供使用的mysql版本 Please provide the mysql version used
> > > > > mysql数据库版本
> > > > > 本地库：8.0.35（正常）
> > > > > 测试库：8.0.32（异常）
> > > > > mysql连接驱动版本：8.0.22
> > > 
> > > 
> > > 后续版本中对mysql 8 XA模式的处理有优化，请升级seata版本后再试。 The handling of mysql 8 XA mode is optimized in subsequent releases, please upgrade the seata version and try again.
> > 
> > 
> > 我们现在用的Seata版本是1.5.2，Seata服务的版本要跟随SpringCloud版本(2021.0.4)，否则会出现不兼容的情况。而且为何本地调试正常，测试环境还是一样的配置为何会有这样的问题？
> 
> mysql 8 在某个版本对XA做了调整。Seata新版本已经做了兼容，请升级后再试。
> 
> Seata没有强绑定SpringCloud版本，只需要确保DataSourceProxyXA正常代理数据源即可。参考：https://seata.io/zh-cn/docs/ops/deploy-guide-beginner#%E4%B8%9A%E5%8A%A1%E7%B3%BB%E7%BB%9F%E9%9B%86%E6%88%90client

我当前Seata版本是1.5.2，要升级2.0版本么？

**Comment by liuqiufeng** [comment]
> > > > > > 请提供使用的mysql版本 Please provide the mysql version used
> > > > > > mysql数据库版本
> > > > > > 本地库：8.0.35（正常）
> > > > > > 测试库：8.0.32（异常）
> > > > > > mysql连接驱动版本：8.0.22
> > > > 
> > > > 
> > > > 后续版本中对mysql 8 XA模式的处理有优化，请升级seata版本后再试。 The handling of mysql 8 XA mode is optimized in subsequent releases, please upgrade the seata version and try again.
> > > 
> > > 
> > > 我们现在用的Seata版本是1.5.2，Seata服务的版本要跟随SpringCloud版本(2021.0.4)，否则会出现不兼容的情况。而且为何本地调试正常，测试环境还是一样的配置为何会有这样的问题？
> > 
> > 
> > mysql 8 在某个版本对XA做了调整。Seata新版本已经做了兼容，请升级后再试。
> > Seata没有强绑定SpringCloud版本，只需要确保DataSourceProxyXA正常代理数据源即可。参考：https://seata.io/zh-cn/docs/ops/deploy-guide-beginner#%E4%B8%9A%E5%8A%A1%E7%B3%BB%E7%BB%9F%E9%9B%86%E6%88%90client
> 
> 我当前Seata版本是1.5.2，要升级2.0版本么？

一般来说，我们只维护最近的2-3个版本。
Generally, we only maintain the most recent 2-3 releases.

**Comment by liuyaorong** [comment]
> > > > > > > 请提供使用的mysql版本 Please provide the mysql version used
> > > > > > > mysql数据库版本
> > > > > > > 本地库：8.0.35（正常）
> > > > > > > 测试库：8.0.32（异常）
> > > > > > > mysql连接驱动版本：8.0.22
> > > > > 
> > > > > 
> > > > > 后续版本中对mysql 8 XA模式的处理有优化，请升级seata版本后再试。 The handling of mysql 8 XA mode is optimized in subsequent releases, please upgrade the seata version and try again.
> > > > 
> > > > 
> > > > 我们现在用的Seata版本是1.5.2，Seata服务的版本要跟随SpringCloud版本(2021.0.4)，否则会出现不兼容的情况。而且为何本地调试正常，测试环境还是一样的配置为何会有这样的问题？
> > > 
> > > 
> > > mysql 8 在某个版本对XA做了调整。Seata新版本已经做了兼容，请升级后再试。
> > > Seata没有强绑定SpringCloud版本，只需要确保DataSourceProxyXA正常代理数据源即可。参考：https://seata.io/zh-cn/docs/ops/deploy-guide-beginner#%E4%B8%9A%E5%8A%A1%E7%B3%BB%E7%BB%9F%E9%9B%86%E6%88%90client
> > 
> > 
> > 我当前Seata版本是1.5.2，要升级2.0版本么？
> 
> 一般来说，我们只维护最近的2-3个版本。 Generally, we only maintain the most recent 2-3 releases.

seata-server以及seata-spring-boot-starter 版本升级到了1.7.1，问题依然存在

**Comment by liuqiufeng** [comment]
> > > > > > > > 请提供使用的mysql版本 Please provide the mysql version used
> > > > > > > > mysql数据库版本
> > > > > > > > 本地库：8.0.35（正常）
> > > > > > > > 测试库：8.0.32（异常）
> > > > > > > > mysql连接驱动版本：8.0.22
> > > > > > 
> > > > > > 
> > > > > > 后续版本中对mysql 8 XA模式的处理有优化，请升级seata版本后再试。 The handling of mysql 8 XA mode is optimized in subsequent releases, please upgrade the seata version and try again.
> > > > > 
> > > > > 
> > > > > 我们现在用的Seata版本是1.5.2，Seata服务的版本要跟随SpringCloud版本(2021.0.4)，否则会出现不兼容的情况。而且为何本地调试正常，测试环境还是一样的配置为何会有这样的问题？
> > > > 
> > > > 
> > > > mysql 8 在某个版本对XA做了调整。Seata新版本已经做了兼容，请升级后再试。
> > > > Seata没有强绑定SpringCloud版本，只需要确保DataSourceProxyXA正常代理数据源即可。参考：https://seata.io/zh-cn/docs/ops/deploy-guide-beginner#%E4%B8%9A%E5%8A%A1%E7%B3%BB%E7%BB%9F%E9%9B%86%E6%88%90client
> > > 
> > > 
> > > 我当前Seata版本是1.5.2，要升级2.0版本么？
> > 
> > 
> > 一般来说，我们只维护最近的2-3个版本。 Generally, we only maintain the most recent 2-3 releases.
> 
> seata-server以及seata-spring-boot-starter 版本升级到了1.7.1，问题依然存在

请提供完整堆栈信息
Please provide full stack information

**Comment by liuyaorong** [comment]
> > > > > > > > > 请提供使用的mysql版本 Please provide the mysql version used
> > > > > > > > > mysql数据库版本
> > > > > > > > > 本地库：8.0.35（正常）
> > > > > > > > > 测试库：8.0.32（异常）
> > > > > > > > > mysql连接驱动版本：8.0.22
> > > > > > > 
> > > > > > > 
> > > > > > > 后续版本中对mysql 8 XA模式的处理有优化，请升级seata版本后再试。 The handling of mysql 8 XA mode is optimized in subsequent releases, please upgrade the seata version and try again.
> > > > > > 
> > > > > > 
> > > > > > 我们现在用的Seata版本是1.5.2，Seata服务的版本要跟随SpringCloud版本(2021.0.4)，否则会出现不兼容的情况。而且为何本地调试正常，测试环境还是一样的配置为何会有这样的问题？
> > > > > 
> > > > > 
> > > > > mysql 8 在某个版本对XA做了调整。Seata新版本已经做了兼容，请升级后再试。
> > > > > Seata没有强绑定SpringCloud版本，只需要确保DataSourceProxyXA正常代理数据源即可。参考：https://seata.io/zh-cn/docs/ops/deploy-guide-beginner#%E4%B8%9A%E5%8A%A1%E7%B3%BB%E7%BB%9F%E9%9B%86%E6%88%90client
> > > > 
> > > > 
> > > > 我当前Seata版本是1.5.2，要升级2.0版本么？
> > > 
> > > 
> > > 一般来说，我们只维护最近的2-3个版本。 Generally, we only maintain the most recent 2-3 releases.
> > 
> > 
> > seata-server以及seata-spring-boot-starter 版本升级到了1.7.1，问题依然存在
> 
> 请提供完整堆栈信息 Please provide full stack information

com.mysql.cj.jdbc.MysqlXAException: Undetermined error occurred in the underlying Connection - check your data for consistency
	at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:347)
	at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:329)
	at com.mysql.cj.jdbc.MysqlXAConnection.rollback(MysqlXAConnection.java:243)
	at io.seata.rm.datasource.xa.ConnectionProxyXA.xaRollback(ConnectionProxyXA.java:141)
	at io.seata.rm.datasource.xa.ConnectionProxyXA.xaRollback(ConnectionProxyXA.java:132)
	at io.seata.rm.datasource.xa.ResourceManagerXA.finishBranch(ResourceManagerXA.java:115)
	at io.seata.rm.datasource.xa.ResourceManagerXA.branchRollback(ResourceManagerXA.java:100)
	at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:125)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:67)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:63)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131)
	at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:63)
	at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:68)
	at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35)
	at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.handleBranchRollback(RmBranchRollbackProcessor.java:63)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.process(RmBranchRollbackProcessor.java:58)
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:281)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0x2618' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:323)
	... 20 common frames omitted

**Comment by liuqiufeng** [comment]
> > > > > > > > > > 请提供使用的mysql版本 Please provide the mysql version used
> > > > > > > > > > mysql数据库版本
> > > > > > > > > > 本地库：8.0.35（正常）
> > > > > > > > > > 测试库：8.0.32（异常）
> > > > > > > > > > mysql连接驱动版本：8.0.22
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 后续版本中对mysql 8 XA模式的处理有优化，请升级seata版本后再试。 The handling of mysql 8 XA mode is optimized in subsequent releases, please upgrade the seata version and try again.
> > > > > > > 
> > > > > > > 
> > > > > > > 我们现在用的Seata版本是1.5.2，Seata服务的版本要跟随SpringCloud版本(2021.0.4)，否则会出现不兼容的情况。而且为何本地调试正常，测试环境还是一样的配置为何会有这样的问题？
> > > > > > 
> > > > > > 
> > > > > > mysql 8 在某个版本对XA做了调整。Seata新版本已经做了兼容，请升级后再试。
> > > > > > Seata没有强绑定SpringCloud版本，只需要确保DataSourceProxyXA正常代理数据源即可。参考：https://seata.io/zh-cn/docs/ops/deploy-guide-beginner#%E4%B8%9A%E5%8A%A1%E7%B3%BB%E7%BB%9F%E9%9B%86%E6%88%90client
> > > > > 
> > > > > 
> > > > > 我当前Seata版本是1.5.2，要升级2.0版本么？
> > > > 
> > > > 
> > > > 一般来说，我们只维护最近的2-3个版本。 Generally, we only maintain the most recent 2-3 releases.
> > > 
> > > 
> > > seata-server以及seata-spring-boot-starter 版本升级到了1.7.1，问题依然存在
> > 
> > 
> > 请提供完整堆栈信息 Please provide full stack information
> 
> com.mysql.cj.jdbc.MysqlXAException: Undetermined error occurred in the underlying Connection - check your data for consistency at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:347) at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:329) at com.mysql.cj.jdbc.MysqlXAConnection.rollback(MysqlXAConnection.java:243) at io.seata.rm.datasource.xa.ConnectionProxyXA.xaRollback(ConnectionProxyXA.java:141) at io.seata.rm.datasource.xa.ConnectionProxyXA.xaRollback(ConnectionProxyXA.java:132) at io.seata.rm.datasource.xa.ResourceManagerXA.finishBranch(ResourceManagerXA.java:115) at io.seata.rm.datasource.xa.ResourceManagerXA.branchRollback(ResourceManagerXA.java:100) at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:125) at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:67) at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:63) at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131) at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:63) at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:68) at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35) at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150) at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.handleBranchRollback(RmBranchRollbackProcessor.java:63) at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.process(RmBranchRollbackProcessor.java:58) at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:281) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748) Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0x2618' at line 1 at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764) at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:323) ... 20 common frames omitted

请提供从发起全局事务的日志开始，完整流程的日志。最好能附带执行的sql，比如异常里的'0x2618'是sql里的吗？

**Comment by liuyaorong** [comment]
> > > > > > > > > > > 请提供使用的mysql版本 Please provide the mysql version used
> > > > > > > > > > > mysql数据库版本
> > > > > > > > > > > 本地库：8.0.35（正常）
> > > > > > > > > > > 测试库：8.0.32（异常）
> > > > > > > > > > > mysql连接驱动版本：8.0.22
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 后续版本中对mysql 8 XA模式的处理有优化，请升级seata版本后再试。 The handling of mysql 8 XA mode is optimized in subsequent releases, please upgrade the seata version and try again.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我们现在用的Seata版本是1.5.2，Seata服务的版本要跟随SpringCloud版本(2021.0.4)，否则会出现不兼容的情况。而且为何本地调试正常，测试环境还是一样的配置为何会有这样的问题？
> > > > > > > 
> > > > > > > 
> > > > > > > mysql 8 在某个版本对XA做了调整。Seata新版本已经做了兼容，请升级后再试。
> > > > > > > Seata没有强绑定SpringCloud版本，只需要确保DataSourceProxyXA正常代理数据源即可。参考：https://seata.io/zh-cn/docs/ops/deploy-guide-beginner#%E4%B8%9A%E5%8A%A1%E7%B3%BB%E7%BB%9F%E9%9B%86%E6%88%90client
> > > > > > 
> > > > > > 
> > > > > > 我当前Seata版本是1.5.2，要升级2.0版本么？
> > > > > 
> > > > > 
> > > > > 一般来说，我们只维护最近的2-3个版本。 Generally, we only maintain the most recent 2-3 releases.
> > > > 
> > > > 
> > > > seata-server以及seata-spring-boot-starter 版本升级到了1.7.1，问题依然存在
> > > 
> > > 
> > > 请提供完整堆栈信息 Please provide full stack information
> > 
> > 
> > com.mysql.cj.jdbc.MysqlXAException: Undetermined error occurred in the underlying Connection - check your data for consistency at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:347) at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:329) at com.mysql.cj.jdbc.MysqlXAConnection.rollback(MysqlXAConnection.java:243) at io.seata.rm.datasource.xa.ConnectionProxyXA.xaRollback(ConnectionProxyXA.java:141) at io.seata.rm.datasource.xa.ConnectionProxyXA.xaRollback(ConnectionProxyXA.java:132) at io.seata.rm.datasource.xa.ResourceManagerXA.finishBranch(ResourceManagerXA.java:115) at io.seata.rm.datasource.xa.ResourceManagerXA.branchRollback(ResourceManagerXA.java:100) at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:125) at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:67) at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:63) at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131) at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:63) at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:68) at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35) at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150) at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.handleBranchRollback(RmBranchRollbackProcessor.java:63) at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.process(RmBranchRollbackProcessor.java:58) at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:281) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748) Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0x2618' at line 1 at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764) at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:323) ... 20 common frames omitted
> 
> 请提供从发起全局事务的日志开始，完整流程的日志。最好能附带执行的sql，比如异常里的'0x2618'是sql里的吗？

问题已解决，原因是在启动时指定的SEATA_IP为服务名称+命名空间（可能存在特殊字符导致的上述Bug），将SEATA_IP取消配置或者将SEATA_IP设置成可访问的IP地址即可解决该问题。
