### ISSUE TITLE
optimize "edit this page" links

### ISSUE THREAD

**Issue by liuqiufeng** [seata/seata.github.io#758]
The "Edit this page" feature has been added to the official website, but the link is currently pointing to the github file browsing address, which should be optimized to point to the editing address.
目前官网添加了“编辑此页”功能，但目前链接指向github文件浏览地址，应优化为指向编辑地址。

For example: `https://github.com/apache/incubator-seata-website/blob/docusaurus/i18n/zh-cn/docusaurus-plugin-content-docs/version-v2.0/overview/what-is-seata.md`
 should point to 
`https://github.com/apache/incubator-seata-website/edit/docusaurus/i18n/zh-cn/docusaurus-plugin-content-docs/version-v2.0/overview/what-is-seata.md`

**Comment by slievrly** [comment]
already support.
