### ISSUE TITLE
没有部署文档？

### ISSUE THREAD

**Issue by 410919244** [seata/seata.github.io#80]
github上的部署文档被标记为过时，但官网又没有关于部署的文档。。。。希望官网能把部署文档加上

**Comment by zjinlei** [comment]
这周末我整理下

**Comment by helloworlde** [comment]
Will add soon.

**Comment by jacksparrow414** [comment]
希望能把[官网](http://seata.io/zh-cn/docs/user/ormframework.html)的文档补充一下，我看官方好像是说支持springcloud，但是只有dubbo的例子

**Comment by zjinlei** [comment]
> 好像是

https://github.com/seata/seata-samples

**Comment by zjinlei** [comment]
> 希望能把[官网](http://seata.io/zh-cn/docs/user/ormframework.html)的文档补充一下，我看官方好像是说支持springcloud，但是只有dubbo的例子
@jacksparrow414 https://github.com/seata/seata-samples

**Comment by lovepoem** [comment]
Fixed by https://github.com/seata/seata.github.io/pull/81

**Comment by jacksparrow414** [comment]
@zjinlei 蟹蟹

**Comment by helloworlde** [comment]
Had completed in #93
