### ISSUE TITLE
The download url of page changed to: https://seata.apache.org/download

### ISSUE THREAD

**Issue by slievrly** [seata/seata.github.io#910]
The current download page url is:
https://seata.apache.org/unversioned/download/seata-server

It seems that it is not easy to remember, I want to simplify this url, optimized url:
https://seata.apache.org/download

**Comment by Vikash55Kumar** [comment]
@slievrly 
I am intrested sir, please assign me for this task

**Comment by slievrly** [comment]
> @slievrly I am intrested sir, please assign me for this task

Ok, look forward to your PR fix.

**Comment by Vikash55Kumar** [comment]
@slievrly 
i want to connect you on Discord for ask douts.
To redirect url
1. I am using "@docusaurus/plugin-client-redirects" but it require to update  

![update](https://github.com/user-attachments/assets/059b9658-1720-43ab-91e5-590239dde9c0)


2. When I update "@docusaurus" to latest version it  require to replace @import to @use in scss

3. i18n cause this issue 

sir please guid me

**Comment by slievrly** [comment]
> @slievrly i want to connect you on Discord for ask douts. To redirect url
> 
> 1. I am using "@docusaurus/plugin-client-redirects" but it require to update
> 
> ![update](https://private-user-images.githubusercontent.com/140326106/380411725-059b9658-1720-43ab-91e5-590239dde9c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTM5NDQsIm5iZiI6MTcyOTk1MzY0NCwicGF0aCI6Ii8xNDAzMjYxMDYvMzgwNDExNzI1LTA1OWI5NjU4LTE3MjAtNDNhYi05MWU1LTU5MDIzOWRkZTljMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxNDQwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGQxYmRjYzMwYTYxYTk4ZGRlMDU1NDk5MjlkNmU0NWJhNGI3OWFiZjJlNjgyMzEzY2I0MTU0OWRjZDg4M2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VdD2DbDsBV36l0fZ8lfnOVMt1d8LyuTdbUJ-lrhq0QY)

Is it a blocking issue if we don't upgrade, or is it just an update notification?


> 2. When I update "@Docusaurus" to latest version it  require to replace @import to @use in scss
> 3. i18n cause this issue
> 
> sir please guid me

**Comment by Vikash55Kumar** [comment]
@slievrly 
yes sir, it was blocking issue if we don't upgrade
1. It require to update "@Docusaurus" to latest version when i use @docusaurus/plugin-client-redirects
2. But when I try to create build it give error

![dass](https://github.com/user-attachments/assets/2a4d8175-0b5d-4cdd-bf4b-980c2ab32c21)

3. when found this when I reaserch

https://github.com/nolimits4web/swiper/issues/7771

sir review this problem

**Comment by slievrly** [comment]
In the long term, we will use the new version of the Docusaurus framework to meet our functional and stability requirements.  However, during this process, we need to address compatibility issues with the Docusaurus framework, which may result in additional workload for you. If you're willing, I think we can break this down into two issues: 
1. Upgrade Docusaurus to 3.5.x and resolve compatibility issues, such as deprecated @import statements. 
3. Adapt the download URL.

**Comment by Vikash55Kumar** [comment]
@slievrly 
sir. I'm genuinely excited to solve this problem.
Too overcome this problem I upgrade Docusaurus to 3.5.x and replace @import to @use __ as  *;
Error were remove but one issue I face to create build is  

![md](https://github.com/user-attachments/assets/2c0ac687-9a59-4ca3-864b-9712c4ff7b97)

**Comment by Vikash55Kumar** [comment]
@slievrly 
sir  'Cause: Can't parse URL https:// with base unspecified://'  due to many link are unorganise  in '/i18n/en/docusaurus-plugin-content-blog' show above image, I fixed this and build work properly.

To optimize url My first approch @docusaurus/plugin-client-redirects  not work for me, I move to second approach that create new folder in dos folder for sidebars like development but it give error during create build    

![uv](https://github.com/user-attachments/assets/4bbd511c-252c-4f1f-a322-adad59cdd7f1)


Sir does any another method to apply siderbar approach else guide me sir

**Comment by slievrly** [comment]
> @slievrly sir 'Cause: Can't parse URL https:// with base unspecified://' due to many link are unorganise in '/i18n/en/docusaurus-plugin-content-blog' show above image, I fixed this and build work properly.
> 
> To optimize url My first approch @docusaurus/plugin-client-redirects not work for me, I move to second approach that create new folder in dos folder for sidebars like development but it give error during create build
> 
> ![uv](https://private-user-images.githubusercontent.com/140326106/381969325-4bbd511c-252c-4f1f-a322-adad59cdd7f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjY0MTUsIm5iZiI6MTczMTMyNjExNSwicGF0aCI6Ii8xNDAzMjYxMDYvMzgxOTY5MzI1LTRiYmQ1MTFjLTI1MmMtNGYxZi1hMzIyLWFkYWQ1OWNkZDdmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMTU1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTczZjUwNzhhNzdmOTA4MGM1MmU4MmQ1YjMwNGNjMWNhNTE1N2ZhMzkxNzg1MzI4N2EwYzk1ZjM4MzJlYmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZnDgk5qqq7IgixU4FON6O0LtMIqWD_rl8eNnw_EpAhU)
> 
> Sir does any another method to apply siderbar approach else guide me sir

I am very sorry that I have not replied to this issue for quite a long time.

**Comment by Vikash55Kumar** [comment]
@slievrly 
No problem sir,
sir what next ?

**Comment by slievrly** [comment]
> @slievrly sir 'Cause: Can't parse URL https:// with base unspecified://' due to many link are unorganise in '/i18n/en/docusaurus-plugin-content-blog' show above image, I fixed this and build work properly.
> 
> To optimize url My first approch @docusaurus/plugin-client-redirects not work for me, I move to second approach that create new folder in dos folder for sidebars like development but it give error during create build
> 
> ![uv](https://private-user-images.githubusercontent.com/140326106/381969325-4bbd511c-252c-4f1f-a322-adad59cdd7f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTAxNTQsIm5iZiI6MTczMTU4OTg1NCwicGF0aCI6Ii8xNDAzMjYxMDYvMzgxOTY5MzI1LTRiYmQ1MTFjLTI1MmMtNGYxZi1hMzIyLWFkYWQ1OWNkZDdmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMzEwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDUyNmYwN2I4MjE1MDM3YmVhMWVkNTU2MWFiNDZhMDcwZDdjOGYwNzhkYTQ5NGJjYzFjNDEyNzdhZWU1MDI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JH5OZg3Gd1LH63gZ6QDL8QsSMe__yB8i6LhykuKlo38)
> 
> Sir does any another method to apply siderbar approach else guide me sir

Reply to the error in this picture. 
docs is version-specific, blog is version-neutral, so in the previous processing we created a new docusaurus-plugin-content-docs-unversioned folder instead of putting it under docusaurus-plugin-content-docs. Seata's official website has a similar page, I think you can refer to the [community page](https://seata.apache.org/community) to implement the download page.

**Comment by Vikash55Kumar** [comment]
@slievrly 
Sorry sir for the late reply,
Sir due to my college university exam I did not give time on contribution and back to back I am selected for the final round of Smart Indian Hackathon organized by the government of India Narendra Modi. I got 2nd Runner-Up in SIH 2024. 
Now sir, I am free to contribute in open source .
Sir please assign me to contrubute  #675
